name: Deploy to VPS
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }} 
          script: |
            git config --global --add safe.directory /home/${{ secrets.SSH_USER }}/${{ secrets.SSH_PROJECT }}
            cd ${{ secrets.SSH_PROJECT }} 
            git pull origin main 
            npm install 
            npm run build 
            pm2 restart profile-website
